"""The App JWT — the one credential the orchestrator signs for itself.

`gh` cannot authenticate as a GitHub App, so the JWT is minted here and the signature
is the only cryptography in the package. It is therefore checked against a real
implementation rather than against itself: every key *in this file* is generated by
`openssl`, and every signature this module produces is handed back to
`openssl dgst -verify`. A test that verified with the same big-integer arithmetic that
signed would prove only that the code agrees with itself, which is exactly the failure
mode worth ruling out.

What a signature is worth is this file's question alone. The suites above the signer
reach it with the structure `tests/conftest.py` builds — parseable, big enough to pad,
not a real pair — because what they assert is which file was read and what the failure
paths name, never that the bytes that came back verify. See
[ADR 0011](../docs/adr/0011-the-app-jwt-is-signed-in-process.md).
"""

from __future__ import annotations

import base64
import json
import shutil
import subprocess
from collections.abc import Iterator
from pathlib import Path

import pytest

from der_encoding import as_pem, der, der_integer
from my_team.core.app_jwt import (
    JWT_LIFETIME_SECONDS,
    JWT_SKEW_SECONDS,
    PrivateKeyError,
    app_jwt,
)


def openssl(*args: str, stdin: bytes | None = None) -> bytes:
    return subprocess.run(["openssl", *args], input=stdin, capture_output=True, check=True).stdout


@pytest.fixture(scope="module")
def keys(tmp_path_factory: pytest.TempPathFactory) -> Iterator[Path]:
    """One RSA key in both PEM encodings GitHub and its tooling hand out, plus an EC key.

    GitHub downloads PKCS#1 (`BEGIN RSA PRIVATE KEY`); anything that has been through a
    modern `openssl` hands back PKCS#8 (`BEGIN PRIVATE KEY`). Both have to parse, or a
    key that survived a round trip stops signing.
    """
    if shutil.which("openssl") is None:  # pragma: no cover — present on every CI runner
        pytest.skip("the signature is cross-checked against openssl, which is not installed")
    directory = tmp_path_factory.mktemp("keys")
    (directory / "pkcs8.pem").write_bytes(openssl("genrsa", "2048"))
    (directory / "pkcs1.pem").write_bytes(
        openssl("rsa", "-in", str(directory / "pkcs8.pem"), "-traditional")
    )
    (directory / "public.pem").write_bytes(
        openssl("rsa", "-in", str(directory / "pkcs8.pem"), "-pubout")
    )
    (directory / "ec.pem").write_bytes(
        openssl(
            "pkcs8",
            "-topk8",
            "-nocrypt",
            stdin=openssl("ecparam", "-genkey", "-name", "prime256v1", "-noout"),
        )
    )
    yield directory


def pem(keys: Path, name: str) -> str:
    return (keys / f"{name}.pem").read_text()


def decode_segment(segment: str) -> dict[str, object]:
    padded = segment + "=" * (-len(segment) % 4)
    decoded: dict[str, object] = json.loads(base64.urlsafe_b64decode(padded))
    return decoded


def verifies(keys: Path, token: str, tmp_path: Path) -> bool:
    """Ask openssl whether the signature really covers `header.payload`."""
    signing_input, _, signature = token.rpartition(".")
    padded = signature + "=" * (-len(signature) % 4)
    (tmp_path / "sig").write_bytes(base64.urlsafe_b64decode(padded))
    (tmp_path / "msg").write_text(signing_input)
    return (
        subprocess.run(
            [
                "openssl",
                "dgst",
                "-sha256",
                "-verify",
                str(keys / "public.pem"),
                "-signature",
                str(tmp_path / "sig"),
                str(tmp_path / "msg"),
            ],
            capture_output=True,
        ).returncode
        == 0
    )


@pytest.mark.parametrize("encoding", ["pkcs1", "pkcs8"])
def test_openssl_verifies_the_signature(keys: Path, encoding: str, tmp_path: Path) -> None:
    token = app_jwt(pem(keys, encoding), app_id=4652114, now=1_755_000_000)

    assert verifies(keys, token, tmp_path)


def test_both_pem_encodings_of_one_key_sign_identically(keys: Path) -> None:
    # A key that has been through `openssl pkcs8` is the same key, so it is the same
    # token: PKCS#1 v1.5 signing is deterministic, unlike PSS.
    assert app_jwt(pem(keys, "pkcs1"), app_id=1, now=1_755_000_000) == app_jwt(
        pem(keys, "pkcs8"), app_id=1, now=1_755_000_000
    )


def test_the_header_declares_rs256(keys: Path) -> None:
    header, _, _ = app_jwt(pem(keys, "pkcs1"), app_id=1, now=1).split(".")

    assert decode_segment(header) == {"alg": "RS256", "typ": "JWT"}


def test_the_payload_carries_the_app_id_and_a_backdated_issue_time(keys: Path) -> None:
    _, payload, _ = app_jwt(pem(keys, "pkcs1"), app_id=4652114, now=1_755_000_000).split(".")

    assert decode_segment(payload) == {
        "iat": 1_755_000_000 - JWT_SKEW_SECONDS,
        "exp": 1_755_000_000 + JWT_LIFETIME_SECONDS,
        "iss": "4652114",
    }


def test_the_window_stays_inside_the_ten_minutes_github_allows(keys: Path) -> None:
    # GitHub rejects a JWT whose `exp` is more than 600 seconds after its `iat`, and the
    # backdating that absorbs clock skew is spent out of the same budget.
    assert JWT_SKEW_SECONDS + JWT_LIFETIME_SECONDS <= 600
    assert JWT_SKEW_SECONDS > 0


def test_the_segments_are_unpadded_base64url(keys: Path) -> None:
    token = app_jwt(pem(keys, "pkcs1"), app_id=1, now=1)

    assert "=" not in token
    assert "+" not in token
    assert "/" not in token
    assert len(token.split(".")) == 3


@pytest.mark.parametrize(
    ("body", "named"),
    [
        ("not a pem at all", "no PEM block"),
        ("-----BEGIN RSA PRIVATE KEY-----\n-----END RSA PRIVATE KEY-----\n", "empty"),
        ("-----BEGIN RSA PRIVATE KEY-----\n!!!!\n-----END RSA PRIVATE KEY-----\n", "base64"),
        ("-----BEGIN RSA PRIVATE KEY-----\nAAEC\n-----END RSA PRIVATE KEY-----\n", "DER"),
    ],
)
def test_a_key_that_is_not_a_key_is_refused(body: str, named: str) -> None:
    with pytest.raises(PrivateKeyError, match=named):
        app_jwt(body, app_id=1, now=1)


def test_a_key_that_is_not_rsa_is_refused(keys: Path) -> None:
    # An EC key in PKCS#8 has the same outer shape as an RSA one, so nothing but the
    # algorithm identifier distinguishes them before the arithmetic goes wrong.
    with pytest.raises(PrivateKeyError, match="RSA"):
        app_jwt(pem(keys, "ec"), app_id=1, now=1)


def test_a_key_that_is_a_public_key_is_refused(keys: Path) -> None:
    with pytest.raises(PrivateKeyError):
        app_jwt(pem(keys, "public"), app_id=1, now=1)


# ── Hand-built keys, for the shapes openssl will not produce ─────────────────────
#
# Every case below is a DER structure no real key has: a modulus too small to pad, a
# length field wider than an integer, a value claiming more bytes than the key holds.
# They are written out by hand because that is the only way to reach the branches that
# refuse them, with the encoder `tests/der_encoding.py` also builds `rsa_pem` from.


def test_a_modulus_too_small_to_pad_is_refused() -> None:
    key = der(
        0x30,
        der_integer(0) + der_integer(65537) + der_integer(65537) + der_integer(3),
    )

    with pytest.raises(PrivateKeyError, match="too small"):
        app_jwt(as_pem("RSA PRIVATE KEY", key), app_id=1, now=1)


@pytest.mark.parametrize(
    ("body", "named"),
    [
        (b"\x30", "ends where a value was expected"),
        (b"\x30\x85\x00\x00\x00\x00\x00", "unreadable length"),
        (b"\x30\x0a\x00", "runs past the end"),
        (b"\x31\x00", "expected tag 0x30"),
    ],
)
def test_malformed_der_is_named(body: bytes, named: str) -> None:
    with pytest.raises(PrivateKeyError, match=named):
        app_jwt(as_pem("RSA PRIVATE KEY", body), app_id=1, now=1)
