"""What the wheel ships.

The skill payload is package data rather than code, so nothing imports it and nothing
would notice it going missing until `my-team sync` ran in a target repo and installed
an empty payload. This builds the real wheel and looks inside.

The expectation is derived from the source tree rather than written down, so a package
or a payload member added later is covered the moment it exists. A written list would
have to be remembered, and forgetting is the thing being guarded against.
"""

from __future__ import annotations

import contextlib
import shutil
import subprocess
import zipfile
from collections.abc import Iterator
from pathlib import Path

import pytest
from hatchling.build import build_wheel

REPO_ROOT = Path(__file__).resolve().parents[1]

# src layout: the wheel names a member relative to the directory holding the package.
PACKAGE_SOURCE_ROOT = "src"
PACKAGE_DIR = f"{PACKAGE_SOURCE_ROOT}/my_team"
PAYLOAD_PREFIX = "my_team/payload/skills/"

# A throwaway project that builds this same source tree with one member excluded. It is
# written out rather than patched from the real pyproject.toml because a config that
# already carried an `exclude` key would take the patch as a duplicate and fail on TOML
# rather than on the thing under test.
PARTIAL_BUILD_PYPROJECT = f"""\
[project]
name = "my-team"
version = "0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["{PACKAGE_DIR}"]
exclude = ["{PACKAGE_DIR}/payload/skills/**"]
"""


def source_package_members(repo_root: Path) -> set[str]:
    """Every file under the source package, named the way the wheel would name it.

    Git is the authority on what counts as source, because it already knows that
    `__pycache__` and `*.pyc` are leavings and it keeps no list this test has to
    maintain. Untracked-but-not-ignored files count: the wheel ships a payload member
    the moment it is written, so one still waiting to be staged belongs on both sides
    rather than reading as a discrepancy.
    """
    listed = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z", "--", PACKAGE_DIR],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return {path.removeprefix(f"{PACKAGE_SOURCE_ROOT}/") for path in listed.split("\0") if path}


def wheel_package_members(wheel: zipfile.ZipFile) -> set[str]:
    """Everything in the wheel that came from the source tree.

    `.dist-info` is generated by the build, so counting it as a member would make the
    two sides disagree by exactly the files that are supposed to differ.
    """
    return {name for name in wheel.namelist() if not name.partition("/")[0].endswith(".dist-info")}


def build_wheel_at(project_root: Path, output_dir: Path) -> Path:
    """Build a project through the same PEP 517 hook a release goes through."""
    output_dir.mkdir(parents=True, exist_ok=True)
    with contextlib.chdir(project_root):
        return output_dir / build_wheel(str(output_dir))


@pytest.fixture(scope="module")
def wheel_contents(tmp_path_factory: pytest.TempPathFactory) -> Iterator[zipfile.ZipFile]:
    """The wheel this checkout builds."""
    with zipfile.ZipFile(build_wheel_at(REPO_ROOT, tmp_path_factory.mktemp("wheel"))) as wheel:
        yield wheel


def test_the_wheel_ships_every_source_package_member(wheel_contents: zipfile.ZipFile) -> None:
    assert wheel_package_members(wheel_contents) == source_package_members(REPO_ROOT)


def test_the_wheel_ships_a_payload(wheel_contents: zipfile.ZipFile) -> None:
    """Keeps the check above from being satisfied by a payload that is empty on both sides."""
    shipped = wheel_package_members(wheel_contents)

    assert [name for name in shipped if name.startswith(PAYLOAD_PREFIX)]


def test_a_wheel_missing_a_payload_member_fails_the_check(tmp_path: Path) -> None:
    """The check earns its runtime only if a partial wheel actually fails it.

    This source tree is rebuilt under a config carrying one `exclude` line — the shape a
    future partial exclusion would most plausibly arrive in — and the payload members it
    drops have to come back as missing.
    """
    project = tmp_path / "project"
    project.mkdir()
    shutil.copytree(REPO_ROOT / PACKAGE_SOURCE_ROOT, project / PACKAGE_SOURCE_ROOT)
    shutil.copy(REPO_ROOT / ".gitignore", project / ".gitignore")
    (project / "pyproject.toml").write_text(PARTIAL_BUILD_PYPROJECT)
    # source_package_members reads a tree through git, so the copy has to be one.
    subprocess.run(["git", "init", "--quiet"], cwd=project, check=True)
    subprocess.run(["git", "add", "--all"], cwd=project, check=True)

    with zipfile.ZipFile(build_wheel_at(project, tmp_path / "wheel")) as wheel:
        shipped = wheel_package_members(wheel)

    missing = source_package_members(project) - shipped
    assert missing
    assert all(name.startswith(PAYLOAD_PREFIX) for name in missing)


def test_the_wheel_installs_the_console_script(wheel_contents: zipfile.ZipFile) -> None:
    entry_points = next(
        name for name in wheel_contents.namelist() if name.endswith(".dist-info/entry_points.txt")
    )

    assert "my-team = my_team.cli:main" in wheel_contents.read(entry_points).decode()
