#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

TARGET_REPO="${TARGET_REPO:-mcnewcp/personal-assistant}"
ACCOUNT="${ACCOUNT:-mcnewcp}"
CONFIG_DIR="$HOME/.config/my-team"
KEY_DIR="$CONFIG_DIR/keys"

# base64url — no padding, no line wrapping, URL-safe alphabet.
_b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

# mint_jwt PEM APP_ID — a short-lived RS256 JWT, the app's own identity.
# GitHub caps exp - iat at 600s; we use 540 so clock skew can't push us over.
mint_jwt() {
  local pem="$1" app_id="$2" now header payload unsigned sig
  now=$(date +%s)
  header=$(printf '{"alg":"RS256","typ":"JWT"}' | _b64url)
  payload=$(printf '{"iat":%s,"exp":%s,"iss":"%s"}' "$((now - 60))" "$((now + 480))" "$app_id" | _b64url)
  unsigned="${header}.${payload}"
  sig=$(printf '%s' "$unsigned" | openssl dgst -sha256 -sign "$pem" -binary | _b64url)
  printf '%s.%s' "$unsigned" "$sig"
}

# app_api JWT PATH [curl args...] — call the API as the app itself.
app_api() {
  local jwt="$1" path="$2"; shift 2
  curl -sS -H "Authorization: Bearer $jwt" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$@" "https://api.github.com${path}"
}

banner "my-team — register a per-role GitHub App"

# ── Prelude: which role are we registering? ────────────────────────────────
printf '  %sWhich role is this app for?%s %s[reviewer]%s ' "$BOLD" "$RESET" "$DIM" "$RESET"
read -r ROLE || true
ROLE="${ROLE:-reviewer}"
ENV_FILE="$CONFIG_DIR/$ROLE.env"          # non-secret ids only; lives outside every repo
PEM_PATH="$KEY_DIR/$ROLE.pem"
mkdir -p "$KEY_DIR"
chmod 700 "$CONFIG_DIR" "$KEY_DIR"
note "ids → $ENV_FILE   key → $PEM_PATH"
pause "Press Enter to begin."

# ── Stage 1 — register the app (browser only) ─────────────────────────────
stage "Register the GitHub App"
say "This is the long one: one form, then Create. Everything else is quick."
open_url "https://github.com/settings/apps/new"
step "GitHub App name — must be globally unique across GitHub. Try: my-team-$ROLE-$ACCOUNT"
step "Homepage URL — https://github.com/$ACCOUNT/my-team"
step "Webhook — UNCHECK 'Active'. This removes the URL / secret / SSL fields."
say ""
say "Repository permissions (leave every other permission at 'No access'):"
step "Contents ............ Read and write"
step "Issues .............. Read and write"
step "Pull requests ....... Read and write"
say ""
step "Where can this GitHub App be installed? — 'Only on this account'"
step "Click 'Create GitHub App'."
say ""
note "You land on the app's settings page. 'App ID' is near the top, under About."
ask APP_ID "Paste the App ID:"
say ""
note "The slug is the last path segment of that page's URL:"
note "  github.com/settings/apps/<slug>   — also the final breadcrumb."
note "Usually the app name lowercased with spaces hyphenated."
ask APP_SLUG "Paste the app's URL slug:"
write_env APP_ID "$APP_ID"
write_env APP_SLUG "$APP_SLUG"
write_env ROLE "$ROLE"

# ── Stage 2 — private key ─────────────────────────────────────────────────
stage "Generate and store the private key"
say "The PEM downloads once and is never shown again."
open_url "https://github.com/settings/apps/$APP_SLUG#private-key"
step "Scroll to 'Private keys' → click 'Generate a private key'."
step "Your browser downloads a .pem file. Don't move or rename it yet."
pause "Downloaded? Press Enter."

DEFAULT_PEM=$(ls -t "$HOME/Downloads"/*.pem 2>/dev/null | head -n1 || true)
if [[ -n "$DEFAULT_PEM" ]]; then
  say "Newest .pem in ~/Downloads: $DEFAULT_PEM"
  if confirm "Use that one?"; then SRC_PEM="$DEFAULT_PEM"; fi
fi
if [[ -z "${SRC_PEM:-}" ]]; then
  printf '  %sFull path to the downloaded .pem:%s ' "$BOLD" "$RESET"
  read -r SRC_PEM || true
  SRC_PEM="${SRC_PEM/#\~/$HOME}"
fi

if [[ ! -f "$SRC_PEM" ]]; then
  warn "no file at $SRC_PEM"
  SKIPPED+=("move the private key to $PEM_PATH and chmod 600 it")
elif ! openssl rsa -in "$SRC_PEM" -noout 2>/dev/null; then
  warn "$SRC_PEM is not a readable RSA private key"
  SKIPPED+=("store a valid private key at $PEM_PATH")
else
  mv "$SRC_PEM" "$PEM_PATH"
  chmod 600 "$PEM_PATH"
  printf '  %s✓ key stored%s %s (mode 600, outside every repo)\n' "$GREEN" "$RESET" "$PEM_PATH"
fi
pause

# ── Stage 3 — install the app on the target repo ──────────────────────────
stage "Install the App on $TARGET_REPO"
say "Registering an app doesn't grant it anything. Installing it does."
open_url "https://github.com/settings/apps/$APP_SLUG/installations"
step "Click 'Install' next to $ACCOUNT."
step "Choose 'Only select repositories'."
step "Select $TARGET_REPO."
step "Click 'Install'."
pause "Installed? Press Enter."

# ── Stage 4 — verify: sign a JWT, mint an installation token ──────────────
stage "Verify — mint an installation token"
say "Proves the key signs, the app is installed, and the token reaches the repo."

if [[ ! -f "$PEM_PATH" ]]; then
  warn "no key at $PEM_PATH — can't verify. Re-run this wizard once the key is in place."
  SKIPPED+=("verification (mint an installation token)")
else
  JWT=$(mint_jwt "$PEM_PATH" "$APP_ID")

  INSTALLATION_ID=$(app_api "$JWT" /app/installations | jq -r --arg r "$TARGET_REPO" '
      map(select(.account.login == ($r | split("/") | .[0]))) | .[0].id // empty' || true)

  if [[ -z "$INSTALLATION_ID" ]]; then
    warn "the app reports no installation — did stage 3 complete?"
    note "raw response:"
    app_api "$JWT" /app/installations | head -c 600; printf '\n'
    SKIPPED+=("install the app on $TARGET_REPO, then re-run this wizard")
  else
    write_env INSTALLATION_ID "$INSTALLATION_ID"

    TOKEN=$(app_api "$JWT" "/app/installations/$INSTALLATION_ID/access_tokens" \
              -X POST | jq -r '.token // empty' || true)

    if [[ -z "$TOKEN" ]]; then
      warn "could not mint an installation token"
      SKIPPED+=("mint an installation token — check the App ID and key match")
    else
      REPOS=$(GH_TOKEN="$TOKEN" gh api /installation/repositories \
                --jq '.repositories[].full_name' 2>/dev/null || true)
      printf '  %s✓ token minted%s (expires in 1 hour, never written to disk)\n' "$GREEN" "$RESET"
      if printf '%s\n' "$REPOS" | grep -qx "$TARGET_REPO"; then
        printf '  %s✓ token reaches%s %s\n' "$GREEN" "$RESET" "$TARGET_REPO"
      else
        warn "token works but doesn't reach $TARGET_REPO — it sees: ${REPOS:-nothing}"
        SKIPPED+=("re-scope the installation to include $TARGET_REPO")
      fi
    fi
  fi
fi
pause

finish
say "Next: the approval smoke test (issue #15, steps 5-8) — run from Claude:"
note "  open a throwaway PR on $TARGET_REPO as $ACCOUNT, then attempt"
note "  GH_TOKEN=<installation-token> gh pr review <n> --approve"
printf '\n'
