#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Every repo the roles are installed on. The orchestrator repo is in the set
# deliberately when the team is pointed at its own source: it is a target repo like
# any other.
ACCOUNT="${ACCOUNT:-mcnewcp}"
CONFIG_DIR="$HOME/.config/my-team"
KEY_DIR="$CONFIG_DIR/keys"
ROSTER="implementer reviewer judge"

# ── The v0.1 roster ───────────────────────────────────────────────────────
# Three roles, settled in mcnewcp/my-team#7. Role is the only name in play — #10 took
# personas out of v0.1, so the App, the key and the config all share it.
#
# role_permissions ROLE -> one `<permission>=<level>` per line
#
# §5's authority matrix, spelled the way the installation API reports it, and the only
# place this script writes it down: the browser stage reads the labels it tells a human
# to click off this, and the verify stage checks the installation GitHub describes
# against the same three lines. Two spellings of one matrix would drift, and the drift
# would be a wizard that certifies a role it told you to provision differently.
#
# Matched exactly rather than as a floor, because the matrix is two prohibitions as much
# as a grant: the reviewer's `contents=read` is "the reviewer never pushes", and the
# implementer's `issues=read` is "the implementer never files issues".
role_permissions() {
  case "$1" in
    implementer) printf 'contents=write\npull_requests=write\nissues=read\n' ;;
    reviewer)    printf 'contents=read\npull_requests=write\nissues=read\n' ;;
    judge)       printf 'contents=write\npull_requests=write\nissues=write\n' ;;
    *)           return 1 ;;
  esac
}

# permission_label PERMISSION LEVEL — one line of the App form, as GitHub labels it.
permission_label() {
  local name level
  case "$1" in
    contents)      name="Contents" ;;
    pull_requests) name="Pull requests" ;;
    issues)        name="Issues" ;;
    *)             name="$1" ;;
  esac
  case "$2" in
    write) level="Read and write" ;;
    read)  level="Read-only" ;;
    *)     level="No access" ;;
  esac
  printf '%s %s %s' "$name" "$(_dots "$name")" "$level"
}

# _dots NAME — the leader that lines the three permission lines up.
_dots() { printf '%*s' "$((20 - ${#1}))" '' | tr ' ' '.'; }

# permission_problems ROLE GRANTED — which of the role's fixed permissions the
# installation does not carry, one per line; nothing at all when the matrix matches.
# GRANTED is `<permission>=<level>` lines, the shape installation_permissions reads out
# of the API — so this stays plain shell and is checked by a test.
permission_problems() {
  local role="$1" granted="$2" permission level held
  while IFS='=' read -r permission level; do
    [[ -n "$permission" ]] || continue
    held=$(printf '%s\n' "$granted" | sed -n "s/^${permission}=//p" | tail -n1)
    [[ "$held" == "$level" ]] \
      || printf '%s is %s rather than %s\n' "$permission" "${held:-no access}" "$level"
  done < <(role_permissions "$role")
}

# installation_permissions JSON — what one installation grants, as the lines above.
installation_permissions() {
  printf '%s' "$1" | jq -r '.permissions // {} | to_entries[] | "\(.key)=\(.value)"'
}

# installation_repos TOKEN — every repository the installation reaches, one per line.
# Fails when the listing does, rather than answering "none": those are different facts
# about the installation and only one of them is the human's to fix.
#
# `--paginate` because the endpoint answers 30 at a time. Without it a target repo that
# sorts onto the second page reads as one the installation cannot reach — so the wizard
# withholds a config block it has actually earned — while an installation scoped far
# wider than the target set passes as though it were narrow.
installation_repos() {
  GH_TOKEN="$1" gh api /installation/repositories --paginate \
    --jq '.repositories[].full_name' 2>/dev/null
}

# base64url — no padding, no line wrapping, URL-safe alphabet.
_b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

# mint_jwt PEM APP_ID — a short-lived RS256 JWT, the app's own identity.
# GitHub caps exp - iat at 600s; we use 540 so clock skew can't push us over.
mint_jwt() {
  local pem="$1" app_id="$2" now header payload unsigned sig
  now=$(date +%s)
  header=$(printf '{"alg":"RS256","typ":"JWT"}' | _b64url)
  payload=$(printf '{"iat":%s,"exp":%s,"iss":"%s"}' "$((now - 60))" "$((now + 480))" "$app_id" | _b64url)
  unsigned="${header}.${payload}"
  sig=$(printf '%s' "$unsigned" | openssl dgst -sha256 -sign "$pem" -binary | _b64url)
  printf '%s.%s' "$unsigned" "$sig"
}

# app_api JWT PATH [curl args...] — call the API as the app itself. `gh api`
# cannot do this: it sends `Authorization: token` and an App JWT needs Bearer.
app_api() {
  local jwt="$1" path="$2"; shift 2
  curl -sS -H "Authorization: Bearer $jwt" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$@" "https://api.github.com${path}"
}

# _value_in FILE KEY — one recorded id, without disturbing the ENV_FILE in play.
_value_in() {
  [[ -f "$1" ]] || return 1
  local line; line=$(grep -E "^${2}=" "$1" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# clear_env KEY — drop KEY from ENV_FILE. The counterpart to write_env, for a value that
# has stopped being true. Nothing here unwinds a write, so this is how one is unwound.
clear_env() {
  local key="$1" tmp
  [[ -f "$ENV_FILE" ]] || return 0
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  mv "$tmp" "$ENV_FILE"
}

# key_is_a_role_key PATH — a regular file, at mode 600, that openssl reads as an RSA
# private key. All three, because `my-team doctor` blocks on all three and
# `credentials.read_private_key` refuses to read past them.
#
# A regular file and not merely something with the right bits: a 0600 *directory* has
# them too, and everything downstream reads the path as a file. And read back rather
# than assumed: a re-sync never re-downloads the key, so if this does not look at it
# nothing does — the wizard signs with it anyway, openssl fails mid-pipeline, and
# `set -e` takes the whole three-role run down where one named file would do.
key_is_a_role_key() {
  local path="$1" mode
  [[ -f "$path" ]] || return 1
  # `stat` spells this differently on GNU and on BSD, and each writes nothing to stdout
  # when it rejects the other's flag — so trying both in order is safe.
  mode=$(stat -c '%a' "$path" 2>/dev/null || stat -f '%OLp' "$path" 2>/dev/null) || return 1
  # Masked to the low nine bits, because the two spellings disagree above them: GNU `%a`
  # reports setuid, setgid and sticky where BSD `%OLp` drops them, so an unmasked
  # comparison would pass a mode-2600 key on macOS and fail the same key on Linux.
  # `credentials.key_mode` masks to 0o777, and this is the file it will be reading.
  [[ "$mode" =~ ^[0-7]+$ ]] || return 1
  (( (8#$mode & 8#777) == 8#600 )) || return 1
  openssl rsa -in "$path" -noout 2>/dev/null
}

# config_block ROLE — the [roles.ROLE] table to paste into .my-team/config.toml, or a
# comment naming what is still missing. This is what the whole wizard is for: the ids
# GitHub only shows once, in the shape the config parser accepts.
#
# Offered only for a role a verify stage proved end to end and whose key is still a role
# key. Ids alone say only that *some* run once read them: every early return in that
# stage leaves them exactly where they were, and a re-sync never re-downloads the key at
# all. A block that looks finished is one a human pastes without reading it, so a stale
# id is worse here than no block.
config_block() {
  local role="$1" env_file="$CONFIG_DIR/$1.env" key="$KEY_DIR/$1.pem"
  local app_id bot_user_id installation_id missing=""
  app_id=$(_value_in "$env_file" APP_ID || true)
  bot_user_id=$(_value_in "$env_file" BOT_USER_ID || true)
  installation_id=$(_value_in "$env_file" INSTALLATION_ID || true)

  [[ -n "$app_id" ]]          || missing="$missing app_id,"
  [[ -n "$bot_user_id" ]]     || missing="$missing bot_user_id,"
  [[ -n "$installation_id" ]] || missing="$missing installation_id,"
  [[ "$(_value_in "$env_file" VERIFIED || true)" == "$role" ]] \
                              || missing="$missing a verification that finished,"
  key_is_a_role_key "$key"    || missing="$missing a mode-600 key at $key,"

  if [[ -n "$missing" ]]; then
    printf '# [roles.%s] — not ready: missing%s.\n' "$role" "${missing%,}"
    printf '# Re-run this wizard and answer "%s".\n' "$role"
    return 1
  fi

  # `~` rather than the expanded path: config keeps key_path exactly as written so that
  # parsing never depends on $HOME, and expands it where the key is read.
  local shown="$KEY_DIR"
  [[ "$shown" == "$HOME"/* ]] && shown="~${shown#"$HOME"}"

  printf '[roles.%s]\n'                     "$role"
  printf 'app_id          = %s\n'           "$app_id"
  printf 'bot_user_id     = %s\n'           "$bot_user_id"
  printf 'installation_id = %s\n'           "$installation_id"
  printf 'key_path        = "%s/%s.pem"\n'  "$shown" "$role"
}

# ── One role, four stages ─────────────────────────────────────────────────
provision_role() {
  local role="$1" resync="$2"

  ENV_FILE="$CONFIG_DIR/$role.env"      # non-secret ids only; outside every repo
  PEM_PATH="$KEY_DIR/$role.pem"
  APP_ID=$(_value_in "$ENV_FILE" APP_ID || true)
  APP_SLUG=$(_value_in "$ENV_FILE" APP_SLUG || true)
  SRC_PEM=""
  BOT_USER_ID=""
  INSTALLATION_ID=""

  if (( ! resync )); then
    register_app "$role"
    store_key "$role"
    install_app "$role"
  fi
  verify_role "$role"
}

# ── Stage 1 — register the app (browser only) ─────────────────────────────
register_app() {
  local role="$1" _permission _level
  stage "$role · register the GitHub App"
  say "This is the long one: one form, then Create. Everything else is quick."
  open_url "https://github.com/settings/apps/new"
  step "GitHub App name — must be globally unique across GitHub. Use: $role-my-team"
  note "Role-named (#10): v0.1 ships no personas, so the byline is the role itself."
  note "Renaming later is safe — config keys on app_id, never on the name."
  step "Homepage URL — https://github.com/$ACCOUNT/my-team"
  step "Webhook — UNCHECK 'Active'. This removes the URL / secret / SSL fields."
  say ""
  say "Repository permissions for $role — leave every other one at 'No access':"
  # Read off role_permissions rather than written out again: the verify stage checks the
  # installation against those same three lines, and a wizard whose instructions and
  # whose verdict disagreed would certify a role it told you to provision differently.
  while IFS='=' read -r _permission _level; do
    [[ -n "$_permission" ]] && step "$(permission_label "$_permission" "$_level")"
  done < <(role_permissions "$role")
  warn "Set these correctly now — widening them later makes you re-accept the installation."
  say ""
  step "Where can this GitHub App be installed? — 'Only on this account'"
  step "Click 'Create GitHub App'."
  say ""
  note "You land on the app's settings page. 'App ID' is near the top, under About."
  ask APP_ID "Paste the App ID:"
  say ""
  note "The slug is the last path segment of that page's URL:"
  note "  github.com/settings/apps/<slug>   — also the final breadcrumb."
  note "Only used to deep-link the next two stages; the verify stage re-reads it."
  ask APP_SLUG "Paste the app's URL slug:"
  write_env APP_ID "$APP_ID"
  write_env APP_SLUG "$APP_SLUG"   # provisional — the verify stage re-reads it
}

# ── Stage 2 — private key ─────────────────────────────────────────────────
store_key() {
  local role="$1" default_pem
  stage "$role · generate and store the private key"
  say "The PEM downloads once and is never shown again."
  open_url "https://github.com/settings/apps/$APP_SLUG#private-key"
  step "Scroll to 'Private keys' → click 'Generate a private key'."
  step "Your browser downloads a .pem file. Don't move or rename it yet."
  pause "Downloaded? Press Enter."

  default_pem=$(ls -t "$HOME/Downloads"/*.pem 2>/dev/null | head -n1 || true)
  if [[ -n "$default_pem" ]]; then
    say "Newest .pem in ~/Downloads: $default_pem"
    if confirm "Use that one?"; then SRC_PEM="$default_pem"; fi
  fi
  if [[ -z "$SRC_PEM" ]]; then
    printf '  %sFull path to the downloaded .pem:%s ' "$BOLD" "$RESET"
    read -r SRC_PEM || true
    SRC_PEM="${SRC_PEM/#\~/$HOME}"
  fi

  if [[ ! -f "$SRC_PEM" ]]; then
    warn "no file at $SRC_PEM"
    SKIPPED+=("move $role's private key to $PEM_PATH and chmod 600 it")
  elif ! openssl rsa -in "$SRC_PEM" -noout 2>/dev/null; then
    warn "$SRC_PEM is not a readable RSA private key"
    SKIPPED+=("store a valid private key at $PEM_PATH")
  else
    mv "$SRC_PEM" "$PEM_PATH"
    chmod 600 "$PEM_PATH"
    printf '  %s✓ key stored%s %s (mode 600, outside every repo)\n' "$GREEN" "$RESET" "$PEM_PATH"
    note "Outside every repo on purpose: there is nothing to .gitignore, and nothing"
    note 'for a dispatched agent to stage by accident. `my-team doctor` checks the mode.'
  fi
  pause
}

# ── Stage 3 — install the app on the target repos ─────────────────────────
install_app() {
  local role="$1"
  stage "$role · install the App on the target repos"
  say "Registering an app doesn't grant it anything. Installing it does."
  open_url "https://github.com/settings/apps/$APP_SLUG/installations"
  step "Click 'Install' next to $ACCOUNT."
  step "Choose 'Only select repositories'."
  for _r in $TARGET_REPOS; do step "Select $_r"; done
  step "Click 'Install' — and select nothing beyond those."
  pause "Installed? Press Enter."
}

# ── Stage 4 — verify, and read back the ids config will key on ────────────
verify_role() {
  local role="$1" jwt app_json live_slug live_name token repos missing extra proven=1
  local installation granted wrong _line
  stage "$role · verify and record the identity"
  say "Proves the key is a role key and signs, that the app is installed, that it holds"
  say "the authority the role is fixed to and that its token reaches the repo — then"
  say "reads back the ids .my-team/config.toml keys on."

  # The earlier verdict stops counting the moment this one starts. Every return below
  # leaves the recorded ids in place, and a config block emitted from them would read as
  # finished while naming an identity this run never re-proved.
  clear_env VERIFIED

  if ! key_is_a_role_key "$PEM_PATH"; then
    warn "no role key at $PEM_PATH — it must be an RSA private key at mode 600."
    note "A re-sync never re-downloads the key, so this is the one place it is checked."
    SKIPPED+=("$role: store the private key at $PEM_PATH and chmod 600 it")
    pause; return 0
  fi

  jwt=$(mint_jwt "$PEM_PATH" "$APP_ID")

  # Ask the App who it is. Names are editable, so a stored slug goes stale on every
  # rename while the numeric ids never move — which is exactly why the slug is never
  # the identity handle.
  app_json=$(app_api "$jwt" /app || true)
  live_slug=$(printf '%s' "$app_json" | jq -r '.slug // empty')
  live_name=$(printf '%s' "$app_json" | jq -r '.name // empty')

  if [[ -z "$live_slug" ]]; then
    warn "the App didn't answer as itself — check that the App ID and key match."
    note "raw response:"; printf '%s' "$app_json" | head -c 400; printf '\n'
    SKIPPED+=("$role: verification (GET /app returned nothing usable)")
    pause; return 0
  fi

  printf '  %s✓ app%s %s  %s(slug %s)%s\n' "$GREEN" "$RESET" "$live_name" "$DIM" "$live_slug" "$RESET"
  if [[ -n "$APP_SLUG" && "$APP_SLUG" != "$live_slug" ]]; then
    note "stored slug was '$APP_SLUG' — refreshed to '$live_slug'"
  fi
  APP_SLUG="$live_slug"
  write_env ROLE "$role"
  write_env APP_SLUG "$APP_SLUG"
  if [[ "$live_name" != "$role-my-team" ]]; then
    warn "App is named '$live_name', but #10 wants '$role-my-team' for the $role role."
    SKIPPED+=("rename the App to $role-my-team (ids and installation survive a rename)")
  fi

  # The bot user id is the actor recorded on reviews, and it is NOT derivable from
  # app_id. `gh` reports the login as '<slug>' while REST reports '<slug>[bot]' (#9),
  # so a login comparison across surfaces silently matches nothing — the state machine
  # matches on this number alone.
  BOT_USER_ID=$(gh api "/users/${APP_SLUG}%5Bbot%5D" --jq '.id' 2>/dev/null || true)
  if [[ -n "$BOT_USER_ID" ]]; then
    write_env BOT_USER_ID "$BOT_USER_ID"
    printf '  %s✓ bot user%s %s[bot] → id %s\n' "$GREEN" "$RESET" "$APP_SLUG" "$BOT_USER_ID"
  else
    warn "couldn't resolve ${APP_SLUG}[bot] — record the bot user id by hand"
    SKIPPED+=("$role: record BOT_USER_ID: gh api /users/${APP_SLUG}%5Bbot%5D --jq .id")
    proven=0
  fi

  # The whole installation rather than its id alone: `suspended_at` and the permissions
  # it was accepted with come back in the same response, and an installation that
  # resolves is not yet one the loop can act with.
  installation=$(app_api "$jwt" /app/installations | jq -c --arg a "$ACCOUNT" '
      map(select(.account.login == $a)) | .[0] // empty' || true)
  INSTALLATION_ID=$(printf '%s' "$installation" | jq -r '.id // empty' 2>/dev/null || true)

  if [[ -z "$INSTALLATION_ID" ]]; then
    warn "the app reports no installation — did the install stage complete?"
    SKIPPED+=("$role: install the app on $TARGET_REPOS, then re-run this wizard")
    pause; return 0
  fi
  write_env INSTALLATION_ID "$INSTALLATION_ID"

  if [[ -n "$(printf '%s' "$installation" | jq -r '.suspended_at // empty')" ]]; then
    warn "the installation is suspended — every id resolves and it grants $role nothing."
    SKIPPED+=("$role: unsuspend the installation for $APP_SLUG")
    proven=0
  fi

  # Not what the App asks for now — what this installation was accepted with. Widening a
  # permission leaves the installation on the old set until a human re-accepts it, and
  # `my-team doctor` blocks on exactly this comparison.
  granted=$(installation_permissions "$installation")
  wrong=$(permission_problems "$role" "$granted")
  if [[ -n "$wrong" ]]; then
    warn "the installation does not carry the authority the $role role is fixed to:"
    while read -r _line; do [[ -n "$_line" ]] && note "  - $_line"; done <<<"$wrong"
    SKIPPED+=("$role: fix its permissions on the App, then re-accept the installation")
    proven=0
  else
    printf '  %s✓ authority%s matches the %s row\n' "$GREEN" "$RESET" "$role"
  fi

  token=$(app_api "$jwt" "/app/installations/$INSTALLATION_ID/access_tokens" -X POST \
            | jq -r '.token // empty' || true)
  if [[ -z "$token" ]]; then
    warn "could not mint an installation token"
    SKIPPED+=("$role: mint an installation token — check the App ID and key match")
    pause; return 0
  fi

  printf '  %s✓ token minted%s (expires in 1 hour, never written to disk)\n' "$GREEN" "$RESET"
  if ! repos=$(installation_repos "$token"); then
    warn "could not list the repositories the installation reaches."
    note "which is a fact about the request, not about the installation's scope."
    SKIPPED+=("$role: re-run this wizard to check what the installation reaches")
    pause; return 0
  fi
  missing=""
  for _r in $TARGET_REPOS; do
    if printf '%s\n' "$repos" | grep -qx "$_r"; then
      printf '  %s✓ token reaches%s %s\n' "$GREEN" "$RESET" "$_r"
    else
      missing="$missing $_r"
    fi
  done
  if [[ -n "$missing" ]]; then
    warn "the installation does not reach:$missing"
    note "it sees: ${repos:-nothing}"
    SKIPPED+=("$role: re-scope the installation to include$missing")
    proven=0
  fi
  extra=$(printf '%s\n' "$repos" | grep -v '^$' \
            | grep -vxF "$(printf '%s\n' $TARGET_REPOS)" || true)
  if [[ -n "$extra" ]]; then
    warn "the installation is scoped wider than the target set. It also reaches:"
    while read -r r; do [[ -n "$r" ]] && note "  - $r"; done <<<"$extra"
    SKIPPED+=("$role: narrow the installation to: $TARGET_REPOS")
  fi

  # Recorded last and only here: this is the one point at which every id above came back
  # from GitHub in this run, over a key that is still a role key.
  if (( proven )); then
    write_env VERIFIED "$role"
  else
    warn "$role is not fully verified — no config block will be offered for it."
  fi
  pause
}

# Sourcing with MT_WIZARD_LIB=1 defines every function above and stops here, so a test
# can drive a stage, or ask for a config block, without a browser. Everything below is
# the run itself — the questions it opens with, and the loop over roles — which is why
# the stages are defined above a line that has nothing but top-level code beneath it.
if [[ -n "${MT_WIZARD_LIB:-}" ]]; then return 0 2>/dev/null || exit 0; fi

# ── Prelude: which roles, and which of them are already registered? ───────
# This runs before the banner because it decides how many stages there are.
_clear
printf '\n%s%s  my-team — register the per-role GitHub Apps%s\n\n' "$BOLD" "$BLUE" "$RESET"
printf '  %sWhich role?%s %s[all | %s]%s ' \
  "$BOLD" "$RESET" "$DIM" "${ROSTER// / | }" "$RESET"
read -r ANSWER || true
ANSWER="${ANSWER:-all}"

if [[ "$ANSWER" == "all" ]]; then
  ROLES="$ROSTER"
elif role_permissions "$ANSWER" >/dev/null; then
  ROLES="$ANSWER"
else
  printf '\n'
  warn "unknown role '$ANSWER' — the v0.1 roster is ${ROSTER// /, }."
  printf '\n'
  exit 1
fi

# Which repos the installation covers. Defaults to the repo you are standing in, since
# that is the target repo; add the orchestrator repo too when the team is pointed at
# its own source.
DEFAULT_REPOS="${TARGET_REPOS:-$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)}"
printf '\n  %sWhich repos should these Apps reach?%s %s[space-separated]%s\n' \
  "$BOLD" "$RESET" "$DIM" "$RESET"
printf '  %s[Enter keeps: %s]%s ' "$DIM" "${DEFAULT_REPOS:-none}" "$RESET"
read -r TARGET_REPOS || true
TARGET_REPOS="${TARGET_REPOS:-$DEFAULT_REPOS}"
if [[ -z "$TARGET_REPOS" ]]; then
  printf '\n'
  warn "no repos named — the Apps would be installed on nothing."
  printf '\n'
  exit 1
fi

mkdir -p "$KEY_DIR"
chmod 700 "$CONFIG_DIR" "$KEY_DIR"

# Re-sync: an App already registered for a role only needs the verify stage, which
# re-reads every id from the App itself and re-checks the key it will be used with. App
# names are editable, so a stored slug goes stale on every rename — this is the repair
# path, not just a re-check.
RESYNC_ROLES=""
TOTAL_STAGES=1                       # the closing config-block stage
for _role in $ROLES; do
  _known=$(_value_in "$CONFIG_DIR/$_role.env" APP_ID || true)
  if [[ -n "$_known" ]]; then
    printf '\n'
    note "'$_role' is already registered — App ID $_known, key $KEY_DIR/$_role.pem"
    if confirm "Re-sync it (re-read its ids) instead of registering a new App?"; then
      RESYNC_ROLES="$RESYNC_ROLES $_role"
      TOTAL_STAGES=$((TOTAL_STAGES + 1))
      continue
    fi
  fi
  TOTAL_STAGES=$((TOTAL_STAGES + 4))
done

banner "my-team — $(printf '%s' "$ROLES" | tr ' ' ',')"
note "ids → $CONFIG_DIR/<role>.env   keys → $KEY_DIR/<role>.pem"
note "Budget ~6–8 minutes per role. Nothing here expires: private keys do not, and"
note "the ids are numeric, so renaming an App later changes none of them."
pause "Press Enter to begin."

for ROLE in $ROLES; do
  RESYNC=0
  [[ " $RESYNC_ROLES " == *" $ROLE "* ]] && RESYNC=1
  provision_role "$ROLE" "$RESYNC"
done

# ── Closing stage — the config the whole wizard exists to produce ─────────
stage "the config blocks"
say "Paste these into .my-team/config.toml in the target repo, then run"
say "\`my-team doctor\` — it re-checks every id here against the API."
printf '\n'
INCOMPLETE=0
for ROLE in $ROSTER; do
  config_block "$ROLE" || INCOMPLETE=1
  printf '\n'
done
if (( INCOMPLETE )); then
  warn "one or more roles is not provisioned — the config above is not complete yet."
fi

# All three blocks are emitted whichever roles this run touched, because a config missing
# two of them is not one anybody can paste. Which is only honest if it says so: a role
# this run skipped had its key re-checked a moment ago and its ids read from GitHub
# whenever it was last verified.
CARRIED=""
for ROLE in $ROSTER; do
  [[ " $ROLES " == *" $ROLE "* ]] || CARRIED="$CARRIED $ROLE"
done
if [[ -n "$CARRIED" ]]; then
  printf '\n'
  note "carried forward from an earlier run:$CARRIED"
  note "their keys were re-checked just now; their ids were read from GitHub then."
  note '`my-team doctor` re-checks every id above against the API.'
fi
pause

finish
warn "Never paste a private key or an installation token into an issue or a config file."
printf '\n'
